package com.lanfunoe.gocache.dto;

/**
 * 艺术家音频响应DTO
 */
public record ArtistAudiosResponse(
    Integer total,
    java.util.List<AudioItem> data,
    Extra extra
) {
    public record AudioItem(
        Integer videoTrack,
        Long filesizeFlac,
        Integer oldHideFlac,
        Integer playcount,
        Integer status,
        Integer videoFileHead,
        Long filesize320,
        Long rpId,
        Integer bitrateFlac,
        Integer oldHide,
        TransParam transParam,
        Integer payType128,
        java.util.List<?> remarks,
        java.util.Map<String, Object> allPrivsSuper,
        String videoHash,
        Integer isOriginal,
        Integer version,
        String topicUrlHigh,
        Integer identity,
        Long albumId,
        Integer oldCpy320,
        Integer privilegeHigh,
        Integer payType,
        java.util.Map<String, AllPrivs> allPrivs128,
        String topicUrlFlac,
        Integer rpPublish,
        Integer pkgPriceSuper,
        Integer pkgPriceHigh,
        Integer pkgPriceFlac,
        Long videoFilesize,
        Integer priceHigh,
        Integer tmpPrivilege,
        Integer pkgPrice,
        Integer status320,
        Long albumAudioId,
        Integer payTypeSuper,
        Integer oldHide320,
        Integer pkgPrice320,
        String topicRemark,
        Integer payTypeHigh,
        Integer privilege128,
        Long timelength320,
        Integer priceFlac,
        Integer failProcess128,
        String audioName,
        Long timelengthFlac,
        Integer price320,
        Integer payTypeFlac,
        String topicUrl,
        Long cid,
        Integer audioFileHead,
        Long filesizeSuper,
        String topicUrlSuper,
        Integer oldCpySuper,
        java.util.Map<String, Object> allPrivsHigh,
        java.util.Map<String, AllPrivs> allPrivs,
        String topicUrl320,
        Integer mixsongType,
        String rpType320,
        String hash,
        String authorName,
        java.util.Map<String, Object> allPrivsFlac,
        Integer failProcessHigh,
        Integer statusFlac,
        Long audioId,
        Integer status128,
        Integer price128,
        String rpTypeFlac,
        Integer payType320,
        java.util.Map<String, Object> allPrivs320,
        Long timelengthHigh,
        Long filesize128,
        String rpTypeSuper,
        String albumName,
        String rpTypeHigh,
        String topicUrl128,
        String rpType128,
        Long songid,
        String rpType,
        Integer failProcessSuper,
        String extnameSuper,
        Integer statusHigh,
        String publishDate,
        String hash320,
        Integer bitrateSuper,
        String hashHigh,
        String extname,
        Integer failProcess320,
        Integer failProcess,
        Integer oldCpyHigh,
        Long timelengthSuper,
        Integer oldCpyFlac,
        Integer level,
        Integer oldHideSuper,
        Integer privilegeFlac,
        Integer oldCpy,
        Integer statusSuper,
        Integer oldCpy128,
        Integer oldHide128,
        Long videoTimelength,
        Integer bitrate,
        String cdUrl,
        Integer privilege320,
        Integer pkgPrice128,
        Integer price,
        Long filesizeHigh,
        Long filesize,
        Long timelength128,
        Integer priceSuper,
        Integer hasObbligato,
        String hash128,
        String albumAudioRemark,
        Integer bitrateHigh,
        Integer failProcessFlac,
        String hashFlac,
        Integer oldHideHigh,
        String hashSuper,
        Long timelength,
        Integer privilege,
        Integer privilegeSuper,
        Long videoId
    ) {
        public record TransParam(
            Integer payBlockTpl,
            java.util.Map<String, Object> qualitymap,
            String unionCover,
            String songnameSuffix,
            Long cid,
            String language,
            Long cpyAttr0,
            java.util.Map<String, Long> ipmap,
            java.util.Map<String, Long> classmap,
            Integer musicpackAdvance,
            Integer display,
            Integer displayRate
        ) {}

        public record AllPrivs(
            Integer failProcess,
            Integer privilege,
            Integer status
        ) {}
    }

    public record Extra(
        Integer pageTotal,
        Integer group
    ) {}
}